require 'resources/resource'
require 'resources/file'
require 'resources/dir'
require 'resources/package'
require 'resources/cloud'
require 'remote_instance'
require 'actors/healer'
require 'actors/instance'
require 'map'

CLOUD_UUID_PATH = '/healing/cloud_uuid'
