require 'utilities/threading'
require 'clouds/element.rb'
require 'clouds/resources/file'
require 'clouds/resources/dir'
require 'clouds/resources/package'
require 'clouds/resources/gem'
require 'clouds/resources/execute'
require 'clouds/cloud'
require 'clouds/root'
require 'clouds/lingo'
require 'app/base'
require 'app/worker'
require 'remoters/remoter'
require 'remoters/ec2'
require 'remoters/instance'
require 'remoters/volume'

CLOUD_UUID_PATH = '/healing/cloud_uuid'
